### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by adrian-rt** [mandiant/route-sixty-sink#1]
What sort of dll should be passed to the -i paramater?

I tried multiple dlls on a project I'm currently running on and always get an error:

adrian@adrian-XPS-15-9570:~/Downloads/clients/clientX$ dotnet run -- aspnetcore -i drop/XYZ123.dll 
Couldn't find a project to run. Ensure a project exists in /home/adrian/Downloads/clients/clientX, or pass the path to the project using --project.

**Comment by dillonfranke** [comment]
Hi @adrian-rt! Thanks for reaching out. That seems to be an error with running the Route Sixty-Sink project itself. Are you in the directory where the `RouteSixtySink.csproj` file exists? It should look like this:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/24629515/180102002-a4dba3fb-9946-4435-b85c-64f1c5f60a80.png">
Then, just give the full path to your `XYZ123.dll` DLL as the `-i` input! Let me know if you have any additional issues.

**Comment by adrian-rt** [comment]
@dillonfranke  thanks, I would have never guess that.

I ran it like this:
sudo dotnet run -- aspnetcore sinkfinder -i ~/Downloads/test 
but the output seems identical to running routefinder.......nothing is flagged, not even a false positive, which I find quite strange since this is a pretty big app.....

thanks.
