### ISSUE TITLE
sinkfinder not supported?

### ISSUE THREAD

**Issue by adrian-rt** [mandiant/route-sixty-sink#2]
Hi,

I ran it like this:

sudo dotnet run -- aspnetcore sinkfinder -i ~/Downloads/project

I got the same result as I get by default with routerunner, I just got a list of routes back.

How do I actually get the sinks? 

Thanks.

**Comment by JohnWoodman** [comment]
Based on your description, it seems like the .NET application didn't have any sinks to alert on, which is why the output looks similar to routefinder. You can edit the sinks.json to add your own sink functions too if you're looking for a specific function.
